### ISSUE TITLE
[BUG] "Unread" notification telling me I have way more unread than I do

### ISSUE THREAD

**Issue by gollygamma** [CherpChat/IssueBoard#11]
**Describe the bug**
I noticed a while back that my "Unread" notification on Cherp was always two posts higher than usual. I just ignored it, but now it's climbed to four and then five posts ahead. For example, if I have four unread messages, it would say I have nine unread messages. The number's gone up twice and I suspect it might keep climbing.

**To Reproduce**
Go to main page. Click on unread posts. See that the number isn't accurate to the actual number of posts.

**Expected behavior**
I expected to have the unread posts be equal to how many actual unread posts there are.

**Desktop (please complete the following information):**
 - OS: Mac Big Sur (but it was an issue on earlier OSes as well)
 - Browser: Firefox
 - Version: 11.1

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS
 - Browser: Safari
 - Version: 13.6

**Comment by two-keys** [comment]
Currently, on `https://cherp.chat/`, ended chats count towards your unread count if you haven't clicked on them/checked them out since they were ended. Due to an oversight, though, ended chats don't show up in the `https://cherp.xyz/chats/unread` tab. This has been rectified on the test server and for 3.2.

I want to ask, then:
A) Are there any ended chats in your chat list that you haven't clicked on/checked out since they were ended?
B) How far back is 'a while back'? Was this an issue before 3.0(when the site look changed)?

**Comment by gollygamma** [comment]
> Currently, on `https://cherp.chat/`, ended chats count towards your unread count if you haven't clicked on them/checked them out since they were ended. Due to an oversight, though, ended chats don't show up in the `https://cherp.xyz/chats/unread` tab. This has been rectified on the test server and for 3.2.
> 
> I want to ask, then:
> A) Are there any ended chats in your chat list that you haven't clicked on/checked out since they were ended?
> B) How far back is 'a while back'? Was this an issue before 3.0(when the site look changed)?

Do I need to go through all my chats? Usually I click on ended chats as a matter of course. I just ask since I have a lot of them in my time on the site. Secondly, I believe it was an issue before 3.0.

**Comment by gollygamma** [comment]
As such, I think it's unlikely that there are ended chats that haven't been clicked on.
