### ISSUE TITLE
Chats Disappeared, prompts remain [BUG]

### ISSUE THREAD

**Issue by magicpixelmemeboy** [CherpChat/IssueBoard#19]
**Describe the bug**
A couple of chats I had with the same user vanished, presumably due to the deletion of their account. No notification of ending, just vanishing chat. However, their prompts still remain in the directory and I can still connect to them.

**To Reproduce**
1. Go to previously answered affected prompt
2. Click on answer
3. New chat exists?

**Expected behavior**
I suppose if an account was deleted, I would assume their prompts would be inaccessible and unanswerable?

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s10
 - Browser: stock browser
 (I don't know where to find OS or version information but it's most recent up to date as of 2/19/2021

**Comment by Woloa** [comment]
I just had this happen to me on my own prompt, I was having a dicussion with the one person who answered, we got a few posts in and then suddenly: Chat not found.

**Comment by two-keys** [comment]
There's been a few issues with account deletion- chats disappearing (and being completely, wholly deleted for everyone involved) after someone deletes their account is intentional. Prompts remaining after someone deletes their account is not: We have a fix in the work, we just need to triple check that our fix won't ruin the database before implementing it.

**Comment by two-keys** [comment]
Should be fixed by now.
