### ISSUE TITLE
[BUG] Blacklist Not Working

### ISSUE THREAD

**Issue by anonymousroleplayer** [CherpChat/IssueBoard#23]
**Describe the bug**
There are things in the blacklist that are still showing up in the directory.

**To Reproduce**
1. Go to Directory
2. Click on Blacklist
3. Enter a content warning
4. Submit
5. Go to Directory
6. See blacklisted tags show up (as typed in the blacklist)

**Expected behavior**
It was expected that the blacklist would block out these tags so they would not be seen.

**Screenshots**
[Screenshot of Directory with a blacklisted term](https://cdn.discordapp.com/attachments/641129875092275210/821109829317689394/cherp.png)
[Screenshot of Blacklist with the blacklisted term on it](https://cdn.discordapp.com/attachments/641129875092275210/821110940933292052/Cherp_blacklist.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.90

**Additional context**
I heard by searching around that a similar issue happened to people in June of 2020.

**Comment by two-keys** [comment]
The server goes through a few checks to decide whether or not to display a given prompt. 
1.) Is the prompt blocked? If so, don't display the prompt no matter what's on the user' Whitelist or Blacklist.
2.) Does the prompt contain any tag on the user's Whitelist? If so, display the prompt no matter what's on the user's Blacklist.
3.) Does the prompt contain any tag on the user's Blacklist? If so, don't display the prompt.

Given this order of operations, I think there possibly might be something on your Whitelist tagged in this prompt and others like it- Whitelisting 'Homestuck', for example, would show you any prompt that has 'Homestuck' tagged even if it otherwise would be blocked by tags on your Blacklist.

**Comment by two-keys** [comment]
Haven't heard back on this for a while, and there's been a lot of recent changes to blacklisting. If you're still having issues, feel free to reopen this.
