### ISSUE TITLE
[FEATURE] Reason for Ending Chat feedback option

### ISSUE THREAD

**Issue by ScarFox** [CherpChat/IssueBoard#32]
It used to be a common courtesy to post a quick explanation why you're no longer interested in a roleplay. Now chats just end, even when things seemingly are going very well and tons of planning was involved and it leaves me and I'm sure many others quite frustrated and wondering why? Many of us wonder if we did something wrong, should I give up on this prompt altogether? It really puts me down creatively because there is no closure and I'm left wondering why?

You know when you decide to cancel a subscription service or even decide to delete a social media account it often asks you 'Why have you chosen to leave?' Below that is a multiple choice you can click with things like 'Too expensive', 'Not what I expected', 'Too many ads', etc. So I figure it might be nice if Cherp had something like this open up when one hits the End Chat/Delete Chat button. Simple explanations like 'No longer interested', 'Personal issues', 'Not what we discussed', 'Waiting too long for response.', and of course 'Prefer not to answer' because they still have a right to keep their opinion to themselves.

I also wouldn't mind if there was an 'Other' in those options with a response bubble that allows the user to type a brief personal reason why they've decided to end it. So long as its not bullying or harassment and the response can be reported if it breaks those rules, I see it as constructive criticism if the person had an issue with the play style.

Many of us are here because we love to write. I'm certaon there's quite a few of us that use Cherp as a practice and not entirely as just a hobby. Many of us thrive on feedback, especially in a roleplay when two or more minds are working on something together. When a chat just ends, especially when things seemed to be going really well, it can really shut one down and leave them puzzled for days. I think it would help ease tension if we had just a little closure. Doesn't have to be super detailed or invasive. A short reason gives us a chance at understanding rather than giving no reason and letting our minds run with endless questions. It leaves me personally distracted and feeds into my writers block.

**Comment by MasterSteelblade** [comment]
The biggest issue with this is that if people wanted to give a reason, they'd do so before disconnecting already. All requiring an input would do - even if there was a "prefer not to answer" option - is result in essentially a 1:1 ratio of fewer disconnects to an increased number of ghosts as people with avoidant personalities refrain from ending chats to avoid it, and over time, probably fewer active users because those people can't clean up their chats list so just drop the site. 

This goes double for when people disconnect for reasons other than writing - nobody will take "you give off bad vibes" as constructive criticism, yet it's a perfectly valid reason for someone disconnecting. I can really only see negatives from this in the same way that people take "PLEASE tell me what I did wrong before D/Cing" or hunting down a partner's prompts to ask why they left as warning signs to not connect in the first place, and the people who do want to give feedback already do. 

Chats on the site are transient and always have been, and it's not really fair on people to effectively *demand* an explanation before allowing them to disconnect. Nobody owes others an explanation for it, and if it intereferes with your writing hobby for literal days, that honestly seems more like something that needs to be worked out on an individual level rather than having the site's staff deal with it for you.

**Comment by two-keys** [comment]
Thank you for your suggestion- I don't think we'll be implementing this.

A person can leave a DC message if they're so inclined before hitting the end chat button- there's no functionality stopping that from happening. People simply, in the current Cherp culture, don't want to. Adding an extra step before ending a chat is implying the necessity of a DC message. I don't believe the culture shift this could introduce is something the Cherp team wants, or that we wouldn't hemorrhage users because of it. With this in mind, I would advise stating your preference for DC messages in the OOC of your prompts, if you have investment in the idea of DC messages.

An implementation of this would, additionally, necessitate an extension of the current site rules to this and the active handling of reports about DC messages, the latter of which would take time from the handling of other, potentially more pressing reports.
